name: 'Popeye GitHub Actions'
description: 'Run Popeye (Kubernetes Cluster Sanitizer) report (standard) and tests for minimum score.'
author: 'Diego Montes <kabute@kabute.org>'
branding:
  icon: 'anchor'
  color: 'blue'
runs:
  using: 'docker'
  image: './Dockerfile'
